<?php

/**
 *
 * @param $key
 * @param $message
 * @param $params
 * Implements hook_mail()
 */
function users_module_mail($key, &$message, $params) {
    switch ($key) {
        case 'send_mail':
            $message['from'] = \Drupal::config('system.site')->get('mail');
            $message['subject'] = $params['subject'];
            $message['body'][] = $params['message'];
            drupal_set_message('Письмо отправлено.', 'status');
            break;
    }

}
